#+Title: SAVAPI (Avira) Antivirus Scanner Module for RSpamd
#+Author: Carsten Strotmann


* Overview

This repository contains an updated Lua-Module for the RSpamd
Spam-Filtering System. It is more robust and evaluates more return
codes from the SAVAPI scanner.

* Changes

** making evaluation of SAVAPI return code more robust

Git =fdd9ffd5fed2b2c22d300cd211c2e2020c6ef1bb=

The old code used string comparison to decide on the return code of the
SAVAPI antivirus scanner. However the return string from SAVAPI could
also contain other text such as the filename of an infected file. If
that filename contained a numner that is also a valid returncode
(example: /Buy 200000 v*** pills on this website/) and because the
return code "200" (not infected) is evaluated first before other
return codes, an invected mail could have been passed as /not
infected/.




** adding additional terminal error conditions

The Savapi module can now handle additional terminal return codes

 | Return Code | Description                                                     |
 |-------------+-----------------------------------------------------------------|
 |         220 | connection timeout                                              |
 |         350 | unspecified error, additional details in the SAVAPI scanner log |
 |         404 | too many clients connected                                      |
